version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: idea-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ideaboard
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: idea-backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/ideaboard?schema=public
      PORT: 4000
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    container_name: idea-frontend
    restart: always
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:4000
    ports:
      - "3000:3000"

volumes:
  db-data:
