-- CreateTable
CREATE TABLE "Idea" (
    "id" SERIAL NOT NULL,
    "text" VARCHAR(280) NOT NULL,
    "upvotes" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Idea_pkey" PRIMARY KEY ("id")
);
